bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered/global   # Main odometry
    bt_loop_duration: 50
    default_server_timeout: 20
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: /odometry/filtered/local   # Topic to get instantaneous measurement of speed from
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: False
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.2
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      rotate_to_heading_angular_vel: 0.8
      max_allowed_time_to_collision_up_to_carrot: 0.5
      approach_velocity_scaling_dist: 2.0
      max_angular_accel: 1.0
      transform_tolerance: 0.3

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 7
      height: 7
      footprint: "[ [-0.57, 0.7], [0.57, 0.7], [0.57, -0.7], [-0.57, -0.7] ]"
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: oak0_pointcloud
        oak0_pointcloud:
          topic: /oak0/points
          data_type: PointCloud2
          expected_update_rate: 1.0
          min_obstacle_height: 0.2
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          obstacle_max_range: 7.0
          obstacle_min_range: 1.5
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.3

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 100
      height: 100
      footprint: "[ [-0.57, 0.7], [0.57, 0.7], [0.57, -0.7], [-0.57, -0.7] ]"
      # no static map
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: oak0_pointcloud
        oak0_pointcloud:
          topic: /oak0/points
          data_type: PointCloud2
          expected_update_rate: 1.0
          min_obstacle_height: 0.2
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          obstacle_max_range: 7.0
          obstacle_min_range: 1.5
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.3

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      allow_unknown: true