bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered/global   # Main odometry
    bt_loop_duration: 50
    default_server_timeout: 20
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.0001
    min_y_velocity_threshold: 0.0001
    min_theta_velocity_threshold: 0.0001
    failure_tolerance: 0.3
    transform_timeout: 0.5
    odom_topic: /odometry/filtered/local   # Topic to get instantaneous measurement of speed from
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: False
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.26
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      angular_dist_threshold: 0.785
      forward_sampling_distance: 1.0
      rotate_to_heading_angular_vel: 1.5
      lookahead_dist: 1.0
      max_angular_accel: 1.5
      simulate_ahead_time: 3.0
      transform_tolerance: 0.3

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 1.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[ [-0.5335, 0.686], [0.5335, 0.686], [0.5335, -0.686], [-0.5335, -0.686] ]"
      always_send_full_costmap: True
      track_unknown_space: false
      # no static map
      plugins: ["obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: false
        footprint_clearing_enabled: true
        combination_method: 1
        tf_filter_tolerance: 0.1
        observation_sources: pointcloud_sensor

        pointcloud_sensor:
          topic: /oak1/points
          data_type: PointCloud2
          observation_persistence: 0.0
          expected_update_rate: 5.0
          min_obstacle_height: 0.1
          max_obstacle_height: 5.0
          marking: true
          clearing: true
          obstacle_max_range: 5.0
          obstacle_min_range: 0.0
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0

  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      transform_tolerance: 2.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 100
      height: 100
      footprint: "[ [-0.5335, 0.686], [0.5335, 0.686], [0.5335, -0.686], [-0.5335, -0.686] ]"
      resolution: 0.05
      track_unknown_space: false
      always_send_full_costmap: True
      # no static map
      plugins: ["obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: false
        footprint_clearing_enabled: true
        combination_method: 1
        tf_filter_tolerance: 0.1
        observation_sources: pointcloud_sensor

        pointcloud_sensor:
          topic: /oak1/points
          data_type: PointCloud2
          observation_persistence: 0.0
          expected_update_rate: 2.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          obstacle_max_range: 5.0
          obstacle_min_range: 0.0
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    use_sim_time: False
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true